Added Practitioner class
department-of-veterans-affairs/health-apis-fhir-resources pull request #101
Opened 2020-10-21 17:48 UTC by that-guy-is-it

2020-10-21 20:19 UTC, jblefkove-va commented on us-core-r4/src/main/java/gov/va/api/health/r4/api/resources/Practitioner.java
> +@Schema(description = "https://www.hl7.org/fhir/practitioner.html")
US Core R4 practitioner: http://hl7.org/fhir/us/core/StructureDefinition-us-core-practitioner.html

2020-10-21 20:21 UTC, jblefkove-va commented on us-core-r4/src/main/java/gov/va/api/health/r4/api/resources/Practitioner.java
> +  String language;
missing `text`, `contained`, `extension`, `modifierExtension`

2020-10-21 20:22 UTC, jblefkove-va commented on us-core-r4/src/main/java/gov/va/api/health/r4/api/resources/Practitioner.java
> +  @Valid List<Identifier> identifier;
not empty

2020-10-21 20:32 UTC, jblefkove-va commented on us-core-r4/src/main/java/gov/va/api/health/r4/api/resources/Practitioner.java
> +  @Valid List<Identifier> identifier;
`system` and `value` are required fields inside this `Identifier`, although vanilla R4 does not require them. @ilaflamme-va I think you ran into a similar problem recently? Should this class have its own `Identifier` class with more strict validation?

2020-10-21 20:33 UTC, jblefkove-va commented on us-core-r4/src/main/java/gov/va/api/health/r4/api/resources/Practitioner.java
> +  @Valid List<HumanName> name;
not empty

2020-10-21 20:34 UTC, jblefkove-va commented on us-core-r4/src/main/java/gov/va/api/health/r4/api/resources/Practitioner.java
> +  @Valid List<HumanName> name;
similar to above, `family` is a required field for `HumanName` on this class, but not for general R4

2020-10-21 20:35 UTC, jblefkove-va commented on us-core-r4/src/main/java/gov/va/api/health/r4/api/resources/Practitioner.java
> +    MALE,
lowercase

2020-10-21 20:36 UTC, jblefkove-va commented on us-core-r4/src/main/java/gov/va/api/health/r4/api/resources/Practitioner.java
> +    @NotNull CodeableConcept code;
`@Valid`

2020-10-21 20:37 UTC, jblefkove-va commented
Missing `Bundle` and `Entry` classes

2020-10-22 13:44 UTC, jblefkove-va commented on us-core-r4/src/main/java/gov/va/api/health/r4/api/resources/Practitioner.java
> +  @Valid List<Identifier> identifier;
Found it: https://github.com/department-of-veterans-affairs/health-apis-fhir-resources/pull/99/files

So this class can use the shared R4 classes for `Identifier` and `HumanName`. The additional validations can be specified in custom validation methods on this class.

2020-10-22 22:17 UTC, jblefkove-va commented on us-core-r4/src/main/java/gov/va/api/health/r4/api/resources/Practitioner.java
> +  @AssertTrue(message = "At most one IdentifierClia can be specified.")
this message is not accurate

2020-10-22 22:18 UTC, jblefkove-va commented on us-core-r4/src/main/java/gov/va/api/health/r4/api/resources/Practitioner.java
> +    return identifier.stream().filter(e -> e.system() != null && e.value() != null).count() >= 1;
should verify that *every* identifier has system and value set

2020-10-22 22:18 UTC, jblefkove-va commented on us-core-r4/src/main/java/gov/va/api/health/r4/api/resources/Practitioner.java
> +  @AssertTrue(message = "At most one IdentifierClia can be specified.")
inaccurate message

2020-10-22 22:18 UTC, jblefkove-va commented on us-core-r4/src/main/java/gov/va/api/health/r4/api/resources/Practitioner.java
> +    return name.stream().filter(e -> e.family() != null).count() >= 1;
similarly this should verify that every name has `family `set

2020-10-22 22:21 UTC, jblefkove-va commented
Needs a unit test, plus tests for the custom validations

2020-10-26 18:10 UTC, jblefkove-va commented on us-core-r4/src/test/java/gov/va/api/health/r4/api/samples/SamplePractitioners.java
> +  @Delegate SampleDataTypes dataTypes = SampleDataTypes.get();
Remove this if it is not used

2020-10-26 18:15 UTC, jblefkove-va commented on us-core-r4/src/test/java/gov/va/api/health/r4/api/resources/PractitionerTest.java
> +              i.system("system");
you can chain these together... `i.value(...).system(...)`

2020-10-26 18:17 UTC, ilaflamme-va requested changes

2020-10-26 18:17 UTC, ilaflamme-va commented on us-core-r4/src/main/java/gov/va/api/health/r4/api/resources/Practitioner.java
> +  @Valid @NotEmpty List<Identifier> identifier;
missing validation method for an Identifier:NPI slice.

2020-10-26 18:18 UTC, ilaflamme-va commented on us-core-r4/src/main/java/gov/va/api/health/r4/api/resources/Practitioner.java
> +  @Valid @NotEmpty List<Identifier> identifier;
Your current validation method will throw away good Identifier:NPI slices

2020-10-26 18:20 UTC, that-guy-is-it commented on us-core-r4/src/test/java/gov/va/api/health/r4/api/samples/SamplePractitioners.java
> +  @Delegate SampleDataTypes dataTypes = SampleDataTypes.get();
It is used, though. The delegate is how I get access to the constructors of the types, such as `meta()` and `narrative()`. Is there another way?

2020-10-26 18:22 UTC, jblefkove-va commented on us-core-r4/src/test/java/gov/va/api/health/r4/api/samples/SamplePractitioners.java
> +  @Delegate SampleDataTypes dataTypes = SampleDataTypes.get();
My mistake, I didn't see references to it but missed the `@Delegate`

2020-10-27 15:11 UTC, jblefkove-va commented on us-core-r4/src/main/java/gov/va/api/health/r4/api/resources/Practitioner.java
> +                        && e.system().equals("http://hl7.org/fhir/sid/us-npi"))
how about `"http://hl7.org/fhir/sid/us-npi".equals(e.system())` ?

2020-10-27 15:26 UTC, that-guy-is-it commented on us-core-r4/src/main/java/gov/va/api/health/r4/api/resources/Practitioner.java
> +                        && e.system().equals("http://hl7.org/fhir/sid/us-npi"))
Hmm, I am confused, how would that be better?

2020-10-27 15:39 UTC, jblefkove-va commented on us-core-r4/src/main/java/gov/va/api/health/r4/api/resources/Practitioner.java
> +                        && e.system().equals("http://hl7.org/fhir/sid/us-npi"))
it eliminates the first check

2020-10-27 20:18 UTC, jblefkove-va commented on us-core-r4/src/main/java/gov/va/api/health/r4/api/resources/Practitioner.java
> +    return (validAllSlice ^ validNpiSlice);
It's less clear to me now what this method is checking? Are these the conditions?

1. At least one identifier is present
2. Every identifier has system and value set, unless system is NPI
3. At most one identifier has system NPI

If so, I think it is simpler to keep the conditions separate and return early if necessary, i.e:

1. Return false if there are no identifiers (method already does this)
2. Return false if there is more than one NPI identifier
3. Return true/false if every identifier has system and value set, filtering out those where system is NPI

2020-10-27 20:24 UTC, bschofield-va commented on us-core-r4/src/main/java/gov/va/api/health/r4/api/resources/Practitioner.java
> +    return (validAllSlice ^ validNpiSlice);
10/10 agree, this fails Occam's razor.
I value simple to read code. No points for cleverness.

2020-10-28 14:30 UTC, jblefkove-va commented on us-core-r4/src/main/java/gov/va/api/health/r4/api/resources/Practitioner.java
> +                        || "http://hl7.org/fhir/sid/us-npi".equals(e.system())));
You can simplify this check by filtering out the NPI entries first:
```
    return identifier
        .stream()
        .filter(e -> !"http://hl7.org/fhir/sid/us-npi".equals(e.system()))
        .allMatch(e -> isNotEmpty(e.system()) && isNotEmpty(e.value()));
```

(Also, we are not fully consistent about it, but we often statically import from `StringUtils`. In this case that definitely benefits readability.)

2020-10-28 15:07 UTC, jblefkove-va approved these changes

2020-10-28 15:10 UTC, ilaflamme-va approved these changes

2020-10-28 15:11 UTC, merged