API 4721 Mixed FHIR Custom Deserializer
department-of-veterans-affairs/health-apis-fhir-resources pull request #112
Opened 2021-02-09 20:48 UTC by that-guy-is-it

2021-02-09 21:30 UTC, jblefkove-va commented on us-core-r4/src/test/java/gov/va/api/health/r4/api/bundle/MixedBundleTest.java
> +  void _mixed() {
This test is now redundant, the individual resource round-trip tests have it covered

2021-02-09 21:31 UTC, jblefkove-va commented on us-core-r4/src/test/java/gov/va/api/health/r4/api/bundle/MixedBundleTest.java
> +        OperationOutcome.builder()
Refactor this into `SampleDataTypes`

2021-02-09 21:32 UTC, jblefkove-va commented on us-core-r4/src/main/java/gov/va/api/health/r4/api/resources/Resource.java
> +        return (Resource) mapper.readValue(root.toString(), clazz);
unnecessary cast?

2021-02-09 21:35 UTC, jblefkove-va commented on us-core-r4/src/main/java/gov/va/api/health/r4/api/resources/Resource.java
> +            Map.entry("Bundle", MixedBundle.class),
This entry is not necessary. This solution (vs annotations) sidesteps Bundles being deserialized as Resources.

2021-02-09 21:36 UTC, jblefkove-va commented on us-core-r4/src/test/java/gov/va/api/health/r4/api/bundle/MixedBundleTest.java
> +  void appoointment() {
typo

2021-02-09 21:36 UTC, jblefkove-va commented on us-core-r4/src/test/java/gov/va/api/health/r4/api/bundle/MixedBundleTest.java
> +  public void patient() {
redundant public

2021-02-09 21:36 UTC, jblefkove-va commented on us-core-r4/src/test/java/gov/va/api/health/r4/api/bundle/MixedBundleTest.java
> +  public void location() {
redundant public

2021-02-10 15:30 UTC, jblefkove-va submitted a review, later dismissed

2021-02-11 14:53 UTC, jhulbert-va commented on us-core-r4/src/test/java/gov/va/api/health/r4/api/bundle/MixedBundleTest.java
> +public class MixedBundleTest {
Am I missing the test that does a roundTrip on a mixed bundle with different resources?

Also, unimportant nitpick, a ParamaterizedTest here would have been :ok_hand:

2021-02-11 17:00 UTC, jhulbert-va commented on us-core-r4/src/test/java/gov/va/api/health/r4/api/bundle/MixedBundleTest.java
> +        .isThrownBy(() -> mapper.readValue(bundleJson, MixedBundle.class));
Can't this all just become:
```
assertThatExceptionOfType(JsonMappingException.class)
        .isThrownBy(() -> assertRoundTrip(bundleofPatientWithNullResourceType));
```
?

2021-02-11 17:08 UTC, jblefkove-va commented on us-core-r4/src/test/java/gov/va/api/health/r4/api/bundle/MixedBundleTest.java
> +        .isThrownBy(() -> mapper.readValue(bundleJson, MixedBundle.class));
I think it's worth breaking out to be more explicit about where the exception is coming from; serializing the bundle is fine, it is deserializing specifically that throws the exception.

(And prior to that, the individual resource itself, even with type missing, can still be round tripped successfully.)

2021-02-11 18:14 UTC, jhulbert-va approved these changes
LGTM

2021-02-11 18:40 UTC, jblefkove-va commented on us-core-r4/src/test/java/gov/va/api/health/r4/api/bundle/MixedBundleTest.java
> +        .isThrownBy(() -> mapper.readValue(bundleJson, MixedBundle.class));
On second thought I like your version better

2021-02-11 18:40 UTC, jblefkove-va approved these changes

2021-02-11 18:49 UTC, bschofield-va commented on us-core-r4/src/test/java/gov/va/api/health/r4/api/bundle/MixedBundleTest.java
> +    // Bundled resource requires additional configuration
We might want to note what the additional configuration is. I do worry about the next resource will get added but not meet the new requirements.

2021-02-11 18:50 UTC, bschofield-va commented
We need some sort of document that describes how to add a new resource such that it is compatible with mixed bundles

2021-02-11 19:03 UTC, bschofield-va commented on us-core-r4/src/main/java/gov/va/api/health/r4/api/resources/Resource.java
> +        Map.ofEntries(
Not a fan of maintaining this map. We will forget to add something to it. Instead of maintaining the map, why not assume any class in this package `gov.va.api.health.r4.api.resources` is a candidate resource.

2021-02-11 19:08 UTC, bschofield-va commented on us-core-r4/src/main/java/gov/va/api/health/r4/api/resources/Resource.java
> +      Class<? extends Resource> clazz = CLASS_MAP.get(type);
How about ...
```
clazz = Class.forName(Resource.class.getPackageName() + "." + type);
if (Resource.class.isAssignableFrom(clazz)) { 
  mapper.readValue( ... )
}
throw ...
```

2021-02-11 19:11 UTC, bschofield-va commented on us-core-r4/src/main/java/gov/va/api/health/r4/api/resources/Resource.java
> +      throw new IllegalStateException("Unknown resource type: " + type);
Is it a bad _state_ to know know the resource type. Perhaps throwing a Jackson deserialization exception is more appropriate.

2021-02-11 19:14 UTC, jblefkove-va commented on us-core-r4/src/main/java/gov/va/api/health/r4/api/resources/Resource.java
> +        Map.ofEntries(
I like it. This also makes it more explicit that we are not supporting the `gov.va.api.health.r4.api.bundle` package. (Switching from the `@JsonSubTypes` solution to this one allowed us to avoid the problem of `Patient.Bundle` getting turned into `MixedBundle`. That said, nested bundles, e.g. `Patient.Bundle` inside `MixedBundle`, are still not supported. But it would be straightforward to enhance `ResourceDeserializer.deserialize()` later if we needed to add that.)

2021-02-11 21:10 UTC, that-guy-is-it commented
With this new approach, it is no longer necessary to document anything, as any class that extends `Resource` in the `resources` package should now work with this. Of note is that since this makes it so every Resource is now serializable without much issue, it might be possible to eventually remove `SimpleResource`. I think, anyway. Outside the scope of the story and this PR, but I figured it was worth bringing it up for the future, @bschofield-va

2021-02-11 21:12 UTC, jblefkove-va commented on us-core-r4/src/test/java/gov/va/api/health/r4/api/bundle/MixedBundleTest.java
> +    // Bundled resource requires additional configuration
This comment should be updated

2021-02-11 22:35 UTC, bschofield-va commented
> With this new approach, it is no longer necessary to document anything

43 changed files says otherwise. This is clearly a departure from what we used to do, so it's worth a little documentation on how mixed bundles work and what it means to make the next great new resource mixed compatible..

2021-02-11 22:38 UTC, bschofield-va commented
I'd like a test case for attempting to deserialize an object in a mixed bundle without `@JsonDeserialize(builder = Whatever.WhateverBuilder.class)`

2021-02-11 22:43 UTC, bschofield-va commented
It might be worth updating `RoundTrip.assertRoundTrip(...)` to be `Resource` aware such that when it encounters something that is a resource it perform an additional check of verifying that it is mixed bundled compatible.

I think this is easy to miss.

2021-02-12 12:23 UTC, jblefkove-va commented
I'm looking into a solution that does not require adding `@JsonDeserialize` to every class.

@that-guy-is-it To simplify further review, some of the low impact changes in this PR can be split out into their own branch and merged first. Let's make a separate PR just for standardizing the handling of the `resourceType` field. That is:

- Adding `Builder.Default` to any `resourceType` where it is missing
- Adding `defaultString(resourceType, "Bundle")` to every Bundle constructor
- Removing unnecessary overrides of `resourceType` from the unit tests, e.g. `.resourceType("Coverage")` in `SamplePatients`

2021-02-12 12:47 UTC, jblefkove-va commented
Also I've added [API-5184](https://vajira.max.gov/browse/API-5184) as a follow-up story to look into replacing `SimpleResource` with `Resource` directly.

2021-02-12 16:02 UTC, bschofield-va commented on us-core-r4/src/test/java/gov/va/api/health/r4/api/bundle/MixedBundleTest.java
> +    assertThatExceptionOfType(StackOverflowError.class).isThrownBy(() -> assertRoundTrip(r));
Expecting a Stack Overflow is not acceptable

2021-02-12 16:05 UTC, bschofield-va requested changes
Stack overflow is not ok

2021-02-12 16:39 UTC, jblefkove-va commented
@bschofield-va please take another look

2021-02-12 17:07 UTC, bschofield-va commented on us-core-r4/src/main/java/gov/va/api/health/r4/api/resources/Resource.java
> +      if (type.equals("SimpleResource")) {
Why is this special? That is, why do we specifically look for simple resource? What makes a simple resource so different from every other resource?

2021-02-12 17:08 UTC, jblefkove-va commented on us-core-r4/src/main/java/gov/va/api/health/r4/api/resources/Resource.java
> +      if (type.equals("SimpleResource")) {
it's in a different package

2021-02-12 18:01 UTC, bschofield-va commented on us-core-r4/src/main/java/gov/va/api/health/r4/api/resources/Resource.java
> +      if (type.equals("SimpleResource")) {
Perhaps a comment to explain why so future us still understands?

2021-02-12 18:05 UTC, bschofield-va submitted a review, later dismissed

2021-02-12 18:12 UTC, jblefkove-va approved these changes

2021-02-12 18:16 UTC, merged