API 5005 Parameters Resource
department-of-veterans-affairs/health-apis-fhir-resources pull request #115
Opened 2021-02-12 23:04 UTC by that-guy-is-it

2021-02-15 18:08 UTC, apeirats-va commented on us-core-r4/src/main/java/gov/va/api/health/r4/api/resources/Parameters.java
> +
Not sure about the three `Fhir.CODE` above. I'm thinking these should have their own classes extending either `Element` or `Quantity`. Or maybe just use `Quantity` as the field type?

2021-02-15 18:12 UTC, apeirats-va commented on us-core-r4/src/main/java/gov/va/api/health/r4/api/datatypes/Contributor.java
> +public class Contributor {
Looks like all new metadatatypes should implement the `Element` interface

2021-02-15 18:14 UTC, apeirats-va commented on us-core-r4/src/main/java/gov/va/api/health/r4/api/datatypes/DataRequirement.java
> +  Integer limit;
Are both `@Valid` and `@Min` needed?

2021-02-15 18:16 UTC, apeirats-va commented on us-core-r4/src/main/java/gov/va/api/health/r4/api/datatypes/DataRequirement.java
> +  @Valid List<Element> sort;
Think we need to implement Sort with `path` and `direction` fields

2021-02-15 18:19 UTC, apeirats-va commented on us-core-r4/src/main/java/gov/va/api/health/r4/api/datatypes/DataRequirement.java
> +  @Valid Subject subject;
Doesn't look like `subject[x]` requires its own class. Just the `subjectCodeableConcept` and `subjectReference`. Otherwise you end up with a json key of `data.subject.subjectReference` instead of the expected `data.subjectReference`

2021-02-15 18:22 UTC, apeirats-va commented on us-core-r4/src/main/java/gov/va/api/health/r4/api/datatypes/Expression.java
> +  String description;
The `@Valid` on Strings shouldn't be necessary

2021-02-15 18:28 UTC, apeirats-va commented on us-core-r4/src/main/java/gov/va/api/health/r4/api/datatypes/TriggerDefinition.java
> +  @Valid Timing timing;
Similar to my other comment regarding `Subject`. The `Timing` wrapper shouldn't be necessary. You can move the `timing[x]` fields up here, and move the `@ZeroOrOneOf` constraint to this class.

2021-02-15 18:30 UTC, apeirats-va commented on us-core-r4/src/main/java/gov/va/api/health/r4/api/datatypes/TriggerDefinition.java
> +  @Valid Timing timing;
By the way, the actual `Timing` datatype is a bit more complex. Lucky for you it's already implemented!

2021-02-16 21:27 UTC, apeirats-va commented on us-core-r4/src/test/java/gov/va/api/health/r4/api/samples/SampleParameters.java
> +        .build();
Let's add a few more parameters to this sample. One for each: `valueBoolean`, `valueString`, `valueResource`.

Maybe an example that uses the `part` field, example here: https://www.hl7.org/fhir/R4/parameters-example.json.html

2021-02-16 21:30 UTC, apeirats-va commented on us-core-r4/src/test/java/gov/va/api/health/r4/api/samples/SampleParameters.java
> +
Let's add some VC request/response samples too:

`vcRequest()` looks something like this:
```
{
  "resourceType": "Parameters",
  "parameter": [{
    "name": "credentialType",
    "valueUri": "https://smarthealth.cards#covid19"
  }, {
    "name": "includeIdentityClaim",
    "valueString": "Patient.name"
  }]
}
```

And `vcResponse()`:

```
{
  "resourceType": "Parameters",
  "parameter":[{
    "name": "verifiableCredential",
    "valueString": "<<Health Cards as JWS>>"
  }]
}
```

2021-02-17 16:29 UTC, apeirats-va commented on us-core-r4-examples/src/main/java/gov/va/api/health/r4/api/swaggerexamples/SwaggerParameters.java
> +
@jblefkove-va I had asked Adrian to add some VC request/response samples here, but now I'm thinking that's not a good idea.

These samples should probably be removed from this repo, and instead implemented on the smart-cards side and linked through the OpenApi definitions there.

2021-02-17 16:34 UTC, jblefkove-va commented on us-core-r4-examples/src/main/java/gov/va/api/health/r4/api/swaggerexamples/SwaggerParameters.java
> +
Agreed

2021-02-17 18:35 UTC, jblefkove-va commented on us-core-r4/src/main/java/gov/va/api/health/r4/api/resources/Parameters.java
> +            + ":gov.va.api.health.r4.api.swaggerexamples.SwaggerParameters#parameters}")
This example should also be removed

2021-02-17 18:52 UTC, jblefkove-va commented on us-core-r4/src/main/java/gov/va/api/health/r4/api/resources/Parameters.java
> +    @Valid Quantity valueDuration;
Duration?

2021-02-17 19:00 UTC, jblefkove-va commented on us-core-r4/src/main/java/gov/va/api/health/r4/api/datatypes/DataRequirement.java
> +  String type;
NotBlank

2021-02-17 19:03 UTC, jblefkove-va commented on us-core-r4/src/main/java/gov/va/api/health/r4/api/datatypes/DataRequirement.java
> +  public static class CodeFilter implements Element {
This should be defined before `DateFilter`

2021-02-17 19:04 UTC, jblefkove-va commented on us-core-r4/src/main/java/gov/va/api/health/r4/api/datatypes/DataRequirement.java
> +    String direction;
path and direction are both required

2021-02-17 19:07 UTC, jblefkove-va commented on us-core-r4/src/main/java/gov/va/api/health/r4/api/datatypes/ParameterDefinition.java
> +  String use;
Looks like this can be an enum

2021-02-17 19:09 UTC, jblefkove-va commented on us-core-r4/src/main/java/gov/va/api/health/r4/api/datatypes/RelatedArtifact.java
> +  String type;
this can be an enum

2021-02-17 19:09 UTC, jblefkove-va commented on us-core-r4/src/main/java/gov/va/api/health/r4/api/datatypes/RelatedArtifact.java
> +  @Pattern(regexp = Fhir.URI)
URL

2021-02-17 19:10 UTC, jblefkove-va commented on us-core-r4/src/main/java/gov/va/api/health/r4/api/datatypes/RelatedArtifact.java
> +  @Pattern(regexp = Fhir.URI)
canonical

2021-02-17 19:11 UTC, jblefkove-va commented on us-core-r4/src/main/java/gov/va/api/health/r4/api/datatypes/TriggerDefinition.java
> +@Schema(description = "https://www.hl7.org/fhir/R4/metadatatypes.html#triggerdefinitionz")
stray char at end

2021-02-17 19:12 UTC, jblefkove-va commented on us-core-r4/src/main/java/gov/va/api/health/r4/api/datatypes/TriggerDefinition.java
> +  String type;
enum

2021-02-17 19:13 UTC, jblefkove-va commented on us-core-r4/src/main/java/gov/va/api/health/r4/api/datatypes/TriggerDefinition.java
> +  @Valid Timing timing;
cruft?

2021-02-17 19:13 UTC, jblefkove-va commented on us-core-r4/src/main/java/gov/va/api/health/r4/api/datatypes/TriggerDefinition.java
> +  @Valid DataRequirement data;
The four timing fields should go before `data`

2021-02-17 19:14 UTC, jblefkove-va commented on us-core-r4/src/main/java/gov/va/api/health/r4/api/datatypes/TriggerDefinition.java
> +  @Valid DataRequirement data;
this is a list

2021-02-17 19:14 UTC, jblefkove-va commented on us-core-r4/src/main/java/gov/va/api/health/r4/api/datatypes/TriggerDefinition.java
> +  Reference timingReference;
`@Valid`

2021-02-17 19:14 UTC, jblefkove-va commented on us-core-r4/src/main/java/gov/va/api/health/r4/api/datatypes/TriggerDefinition.java
> +  Timing timingTiming;
`@Valid`

2021-02-17 19:15 UTC, jblefkove-va requested changes
see inline

2021-02-17 20:16 UTC, jblefkove-va commented on us-core-r4/src/main/java/gov/va/api/health/r4/api/datatypes/TriggerDefinition.java
> +  @Valid Type type;
`@NotNull`

2021-02-17 20:18 UTC, jblefkove-va commented on us-core-r4/src/main/java/gov/va/api/health/r4/api/datatypes/TriggerDefinition.java
> +    namedEvent,
these need to exactly match the spec, e.g. `@JsonProperty("named-event") named_event`

2021-02-17 20:30 UTC, jblefkove-va commented on us-core-r4/src/test/java/gov/va/api/health/r4/api/resources/ParametersTest.java
> +  private final SampleKnownTypes types = SampleKnownTypes.get();
unused

2021-02-17 21:43 UTC, jblefkove-va approved these changes

2021-02-17 21:45 UTC, apeirats-va approved these changes

2021-02-17 21:50 UTC, merged