Api 18521 pracitioner converter
department-of-veterans-affairs/health-apis-fhir-resources pull request #255
Opened 2022-11-01 19:08 UTC by KevinCranmer

2022-11-02 13:46 UTC, bcastillomartel-va commented
should we also add the changes to `ConverterRegistries`?

2022-11-03 13:28 UTC, jhulbert-va approved these changes

2022-11-03 15:28 UTC, jblefkove-va requested changes
There is a potential `NullPointerException` for converting `active`; that field is `Boolean` in R4 and `boolean` in DSTU2

2022-11-03 15:45 UTC, jblefkove-va approved these changes

2022-11-03 15:45 UTC, merged