Added Encounter, EncounterTest, and SampleEncounters Classes to appropriate locations on US-Core-R4
department-of-veterans-affairs/health-apis-fhir-resources pull request #83
Opened 2020-09-09 20:44 UTC by that-guy-is-it

2020-09-09 21:00 UTC, jhulbert-va requested changes
Double check your cardinalities

2020-09-09 21:06 UTC, jhulbert-va commented on us-core-r4/src/main/java/gov/va/api/health/uscorer4/api/resources/Encounter.java
> +
Don't forget the `Entry` and `Bundle` inner classes

2020-09-09 21:06 UTC, jhulbert-va commented on us-core-r4/src/test/java/gov/va/api/health/uscorer4/api/resources/EncounterTest.java
> +
Will need a test for bundle as well.

2020-09-10 14:30 UTC, eclendenning-va commented on us-core-r4/src/main/java/gov/va/api/health/uscorer4/api/resources/Encounter.java
> +
Should be `@NotBlank` which is slightly different than `@NotNull`. 

`@NotBlank` means it still can't be null, but it also can't be just whitespace as the string value.

2020-09-10 14:45 UTC, ilaflamme-va commented on us-core-r4/src/main/java/gov/va/api/health/uscorer4/api/resources/Encounter.java
> +  @Valid List<Identifier> identifier;
This field is going to require stronger validation than just `@Valid`.
It's a bit of a unique identifier, in the case that its needs stricter validation on it's internal fields.

Take a look at DiagnosticReport and see if you can figure out how to add additional validation to the `Identifier` field.

2020-09-10 14:49 UTC, jhulbert-va requested changes

2020-09-10 14:49 UTC, jhulbert-va commented on us-core-r4/src/main/java/gov/va/api/health/uscorer4/api/resources/Encounter.java
> +  @NotNull @Builder.Default String resourceType = "Encounter";
For Strings, there is a `NotBlank` annotation that can be used as an extra precaution against blank strings as well as null.

2020-09-10 14:49 UTC, jhulbert-va commented on us-core-r4/src/main/java/gov/va/api/health/uscorer4/api/resources/Encounter.java
> +  @Valid Meta meta;
Nitpick: Can we put this between `id` and `implicitRules` so that it matches the order in the spec?

2020-09-10 14:49 UTC, jhulbert-va commented on us-core-r4/src/main/java/gov/va/api/health/uscorer4/api/resources/Encounter.java
> +  public enum Status {
The `+` after the list in the description actually means there are more valid statuses than those listed. Check out the status binding link in the spec.

2020-09-10 14:49 UTC, jhulbert-va commented on us-core-r4/src/main/java/gov/va/api/health/uscorer4/api/resources/Encounter.java
> +  @NotNull @Valid Coding encounterClass;
In the spec, this field is `class`. Checkout the JsonProperty annotation.

2020-09-10 14:49 UTC, jhulbert-va commented on us-core-r4/src/main/java/gov/va/api/health/uscorer4/api/resources/Encounter.java
> +  @Valid List<CodeableConcept> type;
NotEmpty

2020-09-10 14:49 UTC, jhulbert-va commented on us-core-r4/src/main/java/gov/va/api/health/uscorer4/api/resources/Encounter.java
> +  @Valid Reference subject;
NotNull

2020-09-10 14:49 UTC, jhulbert-va commented on us-core-r4/src/main/java/gov/va/api/health/uscorer4/api/resources/Encounter.java
> +  @NotNull @Valid Period period;
Can be null

2020-09-10 14:49 UTC, jhulbert-va commented on us-core-r4/src/main/java/gov/va/api/health/uscorer4/api/resources/Encounter.java
> +  public static class Bundle extends AbstractBundle<Entry> {
For the sake of readability, can you use `Encounter.Entry`

2020-09-10 14:49 UTC, jhulbert-va commented on us-core-r4/src/main/java/gov/va/api/health/uscorer4/api/resources/Encounter.java
> +    @NotNull @Valid Period period;
Can be null

2020-09-10 14:49 UTC, jhulbert-va commented on us-core-r4/src/main/java/gov/va/api/health/uscorer4/api/resources/Encounter.java
> +    @Valid Reference condition;
NotNull

2020-09-10 14:49 UTC, jhulbert-va commented on us-core-r4/src/main/java/gov/va/api/health/uscorer4/api/resources/Encounter.java
> +    @Valid
Doesnt need the `Valid` annotation

2020-09-10 14:49 UTC, jhulbert-va commented on us-core-r4/src/main/java/gov/va/api/health/uscorer4/api/resources/Encounter.java
> +    @Valid Reference location;
Not null

2020-09-10 14:50 UTC, jblefkove-va commented on us-core-r4/src/main/java/gov/va/api/health/uscorer4/api/resources/Encounter.java
> +  @NotNull @Builder.Default String resourceType = "Encounter";
To reiterate Evan's comment this should be `@NotBlank`

2020-09-10 14:50 UTC, ilaflamme-va commented on us-core-r4/src/main/java/gov/va/api/health/uscorer4/api/resources/Encounter.java
> +  public enum Status {
Missing 2 codes here

2020-09-10 14:50 UTC, jhulbert-va commented on us-core-r4/src/main/java/gov/va/api/health/uscorer4/api/resources/Encounter.java
> +@JsonAutoDetect(isGetterVisibility = JsonAutoDetect.Visibility.NONE)
Should have `fieldVisibility = JsonAutoDetect.Visibility.ANY` as well.

2020-09-10 14:51 UTC, jblefkove-va commented on us-core-r4/src/main/java/gov/va/api/health/uscorer4/api/resources/Encounter.java
> +@JsonAutoDetect(isGetterVisibility = JsonAutoDetect.Visibility.NONE)
```
@JsonAutoDetect(
    fieldVisibility = JsonAutoDetect.Visibility.ANY,
    isGetterVisibility = JsonAutoDetect.Visibility.NONE)
```

2020-09-10 15:03 UTC, jblefkove-va commented on us-core-r4/src/main/java/gov/va/api/health/uscorer4/api/resources/Encounter.java
> +    @NotNull Coding encounterClass;
`@Valid`

2020-09-10 17:47 UTC, jhulbert-va commented on us-core-r4/src/main/java/gov/va/api/health/uscorer4/api/resources/Encounter.java
> +    for (Identifier item : identifier) {
Identifier could be null, you'll want to check that first. In addition, this for loop could be made a lot simpler with a stream.

2020-09-10 18:13 UTC, jhulbert-va commented on us-core-r4/src/main/java/gov/va/api/health/uscorer4/api/resources/Encounter.java
> +        @Valid List<Entry> entry,
`Encounter.Entry`

2020-09-10 20:20 UTC, jhulbert-va requested changes

2020-09-10 20:20 UTC, jhulbert-va commented on us-core-r4/src/main/java/gov/va/api/health/uscorer4/api/resources/Encounter.java
> +      return false;
Null is valid:
```
identifier | SΣI | 0..* 
```

However, if the identifier is set, those fields are also required to be set.

2020-09-10 20:20 UTC, jhulbert-va commented on us-core-r4/src/main/java/gov/va/api/health/uscorer4/api/resources/Encounter.java
> +  @AssertTrue(message = "Encounter Definition is Invalid.")
Can you make this message more specific so we know exactly what happened if it fails?

2020-09-10 20:42 UTC, jhulbert-va approved these changes

2020-09-10 20:57 UTC, merged