API-2318: R4 RelatedPerson model
department-of-veterans-affairs/health-apis-fhir-resources pull request #84
Opened 2020-09-09 21:04 UTC by jjabando1

2020-09-09 21:09 UTC, jhulbert-va requested changes
Samples and Tests

2020-09-09 21:27 UTC, jhulbert-va requested changes

2020-09-09 21:27 UTC, jhulbert-va commented on r4/src/main/java/gov/va/api/health/r4/api/RelatedPersonApi.java
> +public interface RelatedPersonApi {
Can we move this to a "future" directory? Right now, we just want to get the models ready to go. The swagger and API definitions are not necessary right now as we will not be building a controller until later.

2020-09-09 21:27 UTC, jhulbert-va commented on r4/src/main/java/gov/va/api/health/r4/api/resources/RelatedPerson.java
> +  @NotBlank String resourceType;
Can we move this to the top and have a default of "RelatedPerson" (check out Lomboks builder defaults)?

2020-09-09 21:27 UTC, jhulbert-va commented on r4/src/main/java/gov/va/api/health/r4/api/resources/RelatedPerson.java
> +public class RelatedPerson implements Resource {
RelatedPerson actually implements DomainResource

2020-09-09 21:27 UTC, jhulbert-va commented on r4/src/main/java/gov/va/api/health/r4/api/resources/RelatedPerson.java
> +  @Valid List<Address> locationAddress;
This field should be `address` check out the JsonProperty annotation.

2020-09-09 21:27 UTC, jhulbert-va commented on r4/src/main/java/gov/va/api/health/r4/api/resources/RelatedPerson.java
> +
`communication` field.

2020-09-09 21:27 UTC, jhulbert-va commented on r4/src/main/java/gov/va/api/health/r4/api/resources/RelatedPerson.java
> +  public static class Bundle extends AbstractBundle<Coverage.Entry> {
Copy Pasta!

2020-09-10 15:18 UTC, jblefkove-va commented on r4/src/main/java/gov/va/api/health/r4/api/resources/RelatedPerson.java
> +    @NotNull CodeableConcept language;
`@Valid`

2020-09-10 15:18 UTC, ilaflamme-va approved these changes
lgtm

2020-09-10 15:21 UTC, jhulbert-va approved these changes

2020-09-10 15:21 UTC, jhulbert-va commented
:shipit:

2020-09-10 15:23 UTC, merged