deifentification-core
department-of-veterans-affairs/health-apis-fhir-resources pull request #86
Opened 2020-09-10 18:45 UTC by ilaflamme-va

2020-09-10 21:18 UTC, jhulbert-va requested changes

2020-09-10 21:18 UTC, jhulbert-va commented on deidentification-core/src/main/java/gov/va/api/health/deidentification/core/SyntheticData.java
> +  String synthesizeDate(String rawBirthdate);
Nitpick: This should just be `rawDate`. The interface shouldn't know if its a birthdate or not.

2020-09-11 14:39 UTC, ilaflamme-va commented on deidentification-core/pom.xml
> +  <dependencies>
recommendation?

2020-09-14 15:23 UTC, jhulbert-va requested changes

2020-09-14 15:23 UTC, jhulbert-va commented on deidentification-core/pom.xml
> +  <version>4.0.15-SNAPSHOT</version>
Rev this boi

2020-09-14 15:23 UTC, jhulbert-va commented on deidentification-core/pom.xml
> +      <version>1.2.3</version>
Can we pull the rest of these versions into properties?

2020-09-14 15:27 UTC, jhulbert-va commented on deidentification-core/src/main/java/gov/va/api/health/deidentification/core/ResourceBasedSyntheticData.java
> +    if (rawDate == null || rawDate.isEmpty()) {
Should this be `isBlank()`?

2020-09-14 15:52 UTC, jhulbert-va approved these changes

2020-09-14 16:35 UTC, merged