API-2320: R4 Appointment model
department-of-veterans-affairs/health-apis-fhir-resources pull request #87
Opened 2020-09-10 20:49 UTC by jjabando1

Appointment, AppointmentTest, and SampleAppointments classes initialized

2020-09-10 21:12 UTC, ilaflamme-va commented on r4/src/main/java/gov/va/api/health/r4/api/resources/Appointment.java
> +  @Valid @NotNull AppStatus status;
AppointmentStatus

2020-09-10 21:12 UTC, ilaflamme-va commented on r4/src/main/java/gov/va/api/health/r4/api/resources/Appointment.java
> +  public enum PartStatus {
ParticipationStatus

2020-09-10 21:12 UTC, ilaflamme-va commented on r4/src/test/java/gov/va/api/health/r4/api/samples/SampleAppointments.java
> +        .actor(reference())
missing type

2020-09-10 21:12 UTC, ilaflamme-va commented
Small, nitpicks, but otherwise goodjob!

2020-09-10 21:27 UTC, jhulbert-va commented on r4/src/main/java/gov/va/api/health/r4/api/resources/Appointment.java
> +  @Valid
Doesnt need the valid annotation

2020-09-10 21:27 UTC, jhulbert-va commented on r4/src/main/java/gov/va/api/health/r4/api/resources/Appointment.java
> +  @Valid
Doesnt need the valid annotation

2020-09-10 21:28 UTC, eclendenning-va requested changes

2020-09-10 21:28 UTC, eclendenning-va commented on r4/src/main/java/gov/va/api/health/r4/api/resources/Appointment.java
> +          "${r4.apptBundle:gov.va.api.health.r4.api.swaggerexamples.SwaggerAppointment#apptBundle}")
appointmentBundle

2020-09-10 21:37 UTC, jjabando1 commented on r4/src/main/java/gov/va/api/health/r4/api/resources/Appointment.java
> +          "${r4.apptBundle:gov.va.api.health.r4.api.swaggerexamples.SwaggerAppointment#apptBundle}")
I set the example string to "${r4.appointmentBundle:gov.va.api.health.r4.api.swaggerexamples.SwaggerAppointment#appointmentBundle}", but I get a build error: src\main\java\gov\va\api\health\r4\api\resources\Appointment.java:[153] (sizes) LineLength: Line is longer than 100 characters (found 114).

2020-09-11 13:41 UTC, eclendenning-va approved these changes

2020-09-11 13:42 UTC, merged