uscore annotations added to organization model
department-of-veterans-affairs/health-apis-fhir-resources pull request #95
Opened 2020-09-24 17:40 UTC by ilaflamme-va

useful links:
https://build.fhir.org/ig/HL7/US-Core-R4/StructureDefinition-us-core-organization.html
http://hl7.org/fhir/R4/organization.html

2020-09-24 18:07 UTC, jblefkove-va commented on us-core-r4/src/main/java/gov/va/api/health/r4/api/resources/Organization.java
> +  @UsCore
`identifier:CLIA` is not marked as `must be supported`

2020-09-24 18:08 UTC, jblefkove-va commented on us-core-r4/src/main/java/gov/va/api/health/r4/api/resources/Organization.java
>    @Valid List<ContactPoint> telecom;
telecom must be supported?

2020-09-24 19:29 UTC, ilaflamme-va commented on us-core-r4/src/main/java/gov/va/api/health/r4/api/resources/Organization.java
> +  @UsCore
We aren't annotating fields that must be supported (because null is valid). The annotations are for places the models have changed to support us-core, as an upgrade on top of r4.

2020-09-24 19:31 UTC, ilaflamme-va commented on us-core-r4/src/main/java/gov/va/api/health/r4/api/resources/Organization.java
>    @Valid List<ContactPoint> telecom;
There is no change to the model for this, because a null value is legal, even though it says "Must Be Supported".
Must Be Supported does not translate to required.

2020-09-24 19:31 UTC, ilaflamme-va commented on us-core-r4/src/main/java/gov/va/api/health/r4/api/resources/Organization.java
>    @Valid List<ContactPoint> telecom;
The model remains the same for both R4 and UsCoreR4 in this case.

2020-09-24 19:53 UTC, jblefkove-va approved these changes

2020-09-24 20:36 UTC, jhulbert-va requested changes

2020-09-24 20:36 UTC, jhulbert-va commented on us-core-r4/src/main/java/gov/va/api/health/r4/api/resources/Organization.java
> +  @UsCore
Update the annotations with new fields.

2020-09-25 13:05 UTC, closed without merging

2020-09-25 13:06 UTC, ilaflamme-va commented
Closing this, as the focus is on CarinBB at this time.